version: '3'
services:
  main:
    build:
      context: ./main
      args:
        PUID: 1000
        PGID: 100
    container_name: filebrowser
    volumes:
      - /:/srv
    restart: unless-stopped
 
  swap:
    build:
      context: ./swap
      args:
        PUID: 1000
        PGID: 100
    container_name: filebrowser-swap
    volumes:
      - /mnt/4t/swap:/srv
    user: 1000:100
    restart: unless-stopped

networks:
  default:
    name: apps
    external: true
