version: '3'

services:
  app:
    image: nicolargo/glances:latest-full
    container_name: glances
    restart: always
    pid: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      GLANCES_OPT: -w

networks:
  default:
    name: apps
    external: true