version: '3.8'

services:
  aria2pro:
    image: p3terx/aria2-pro
    container_name: aria
    environment:
      - PUID=1000
      - PGID=100
      - UMASK_SET=022
      - RPC_SECRET=
      - RPC_PORT=6800
      - LISTEN_PORT=6888
      - DISK_CACHE=64M
      - IPV6_MODE=true
      - UPDATE_TRACKERS=true
      - CUSTOM_TRACKER_URL=
      - TZ=Asia/Shanghai
    volumes:
      - ./config:/config
      - /mnt/4t/download:/downloads
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: 1m

  AriaNg:
    image: p3terx/ariang
    container_name: aria-ng
    # command: --port 6880 --ipv6
    command: --port 6880
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: 1m

networks:
  default:
    name: apps
    external: true
