version: '3'

services:
  frps:
    image: snowdreamtech/frps
    container_name: frps
    restart: always
    ports:
      - 7000:7000
      - 127.0.0.1:7002:7002
    volumes:
      - ./frps.toml:/etc/frp/frps.toml:ro
      - ../caddy/data/certificates/acme.zerossl.com-v2-dv90/wildcard_.tianze.me:/certs:ro

networks:
  default:
    name: apps
    external: true
