port: 1122
domain: tianze.me
tls:
  cloudflare_token: ${cloudflare_token}
  email: ${email}
auth:
  name: auth
  dial: authelia:9091
services:
  status:
    dial: glances:61208
  media:
    dial: jellyfin:8096
  bt:
    dial: qbittorrent:8080
  bte:
    dial: qbittorrentee:8080
  bitwarden:
    dial: bitwarden:80
  file:
    dial: filebrowser:80
  swap:
    dial: filebrowser-swap:80
  pfile:
    dial: filebrowser-public:80
  sub:
    dial: qzyq-water-sub:8080
  aria:
    dial: aria-ng:6880
    paths:
      /jsonrpc:
        dial: aria:6800
        auth: false
  fs:
    custom_handle:
      - handler: subroute
        routes:
          - match: [{path: ["/${file_server_token}/*"]}]
            handle:
              - handler: rewrite
                strip_path_prefix: "/${file_server_token}"
              - handler: file_server
                root: "${file_server_root}"
                browse: {template_file: /app/browse.html}
  gitp:
    custom_handle:
      - handler: subroute
        routes:
          - match: [{path: ["/${gitee_token}/*"]}]
            handle:
              - handler: reverse_proxy
                rewrite: {strip_path_prefix: "/${gitee_token}"}
                upstreams: [{dial: gitee.com:443}]
                transport: {protocol: http, tls: {}}
                headers: {request: {add: {Host: [gitee.com]}}}

