version: "3.9"

services:
  app:
    build:
      args:
        PUID: 1000
        PGID: 1000
    container_name: caddy
    restart: unless-stopped
    ports:
      - 1111:1111
      - 1111:1111/udp
    volumes:
      - ./caddy.json:/app/config.json:ro
      - ./data:/app/data/caddy
      - /mnt/4t:/mnt/4t:ro

networks:
  default:
    name: apps
    external: true
