version: '3'

services:
  grocy:
    image: linuxserver/grocy
    container_name: grocy
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
    volumes:
      - ./config:/config
    # ports:
    #   - 9283:80
    restart: unless-stopped

networks:
  default:
    name: apps
    external: true