version: '3'

services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: 1000:1000
    volumes:
      - ./config:/config
      - jellyfin_cache:/cache
      - /mnt/4t/media:/media:ro
    restart: unless-stopped

volumes:
  jellyfin_cache:

networks:
  default:
    name: apps
    external: true