version: '3'

services:
  jellyfin:
    image: linuxserver/jellyfin
    container_name: jellyfin
    environment:
      PUID: 1000
      PGID: 100
      TZ: Asia/Shanghai
    volumes:
      - ./config:/config
      - /mnt/4t/media:/media:ro
    restart: unless-stopped

networks:
  default:
    name: apps
    external: true
