version: '3'

services:
  app:
    image: syncthing/syncthing
    container_name: sync
    restart: always
    environment:
      PUID: 1000
      PGID: 1000
    ports:
      # - 127.0.0.1:62488:8384
      - 22000:22000/tcp # TCP file transfers
      - 22000:22000/udp # QUIC file transfers
      # - 21027:21027/udp # Receive local discovery broadcasts
    volumes:
      - /mnt/4t/backup:/var/syncthing

networks:
  default:
    name: apps
    external: true