version: "3"
services:
  navidrome:
    image: deluan/navidrome:latest
    user: 1000:1000
    ports:
      - 127.0.0.1:24533:4533
    restart: unless-stopped
    environment:
      # Optional: put your config options customization here. Examples:
      # ND_SCANSCHEDULE: 1h
      ND_LOGLEVEL: warn  
      # ND_SESSIONTIMEOUT: 24h
      # ND_BASEURL: ""
    volumes:
      - "./data:/data"
      - "/mnt/4t/media/music:/music:ro"