version: "3.8"
services:
  dashy:
    image: lissy93/dashy
    volumes:
      - ./config.yml:/app/public/conf.yml
    ports:
      - 62487:80
    environment:
      - NODE_ENV=production
      - UID=1000
      - GID=1000
    restart: always
    # healthcheck:
    #   test: ['CMD', 'node', '/app/services/healthcheck']
    #   interval: 1m30s
    #   timeout: 10s
    #   retries: 3
    #   start_period: 40s