version: '3'

services:
  qzyq:
    image: tz039e/qzyq-water-sub:v1.0.2
    container_name: qzyq-water-sub
    restart: always
    user: 1000:1000
    volumes:
      - ./db:/db # make sure to create the directory at first
    # ports:
    #   - 127.0.0.1:24329:8080

networks:
  default:
    name: apps
    external: true