version: '3'
secrets:
  JWT_SECRET:
    file: ./secrets/JWT_SECRET
  STORAGE_ENCRYPTION_KEY:
    file: ./secrets/STORAGE_ENCRYPTION_KEY
  NOTIFIER_SMTP_PASSWORD:
    file: ./secrets/NOTIFIER_SMTP_PASSWORD
  IDENTITY_PROVIDERS_OIDC_HMAC_SECRET:
    file: ./secrets/IDENTITY_PROVIDERS_OIDC_HMAC_SECRET
  IDENTITY_PROVIDERS_OIDC_ISSUER_PRIVATE_KEY:
    file: ./secrets/IDENTITY_PROVIDERS_OIDC_ISSUER_PRIVATE_KEY

services:
  authelia:
    container_name: authelia
    image: authelia/authelia:latest
    restart: unless-stopped
    # expose:
    #   - 9091
    secrets:
      - JWT_SECRET
      - STORAGE_ENCRYPTION_KEY
      - NOTIFIER_SMTP_PASSWORD
      - IDENTITY_PROVIDERS_OIDC_HMAC_SECRET
      - IDENTITY_PROVIDERS_OIDC_ISSUER_PRIVATE_KEY
    environment:
      AUTHELIA_JWT_SECRET_FILE: /run/secrets/JWT_SECRET
      AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE: /run/secrets/STORAGE_ENCRYPTION_KEY
      AUTHELIA_NOTIFIER_SMTP_PASSWORD_FILE: /run/secrets/NOTIFIER_SMTP_PASSWORD
      AUTHELIA_IDENTITY_PROVIDERS_OIDC_HMAC_SECRET_FILE: /run/secrets/IDENTITY_PROVIDERS_OIDC_HMAC_SECRET
      AUTHELIA_IDENTITY_PROVIDERS_OIDC_ISSUER_PRIVATE_KEY_FILE: /run/secrets/IDENTITY_PROVIDERS_OIDC_ISSUER_PRIVATE_KEY
    volumes:
      - ./config:/config
    user: 1000:100
    networks:
      - default
      - db

  redis:
    image: redis
    restart: unless-stopped
    volumes:
      - authelia-redis:/data
    networks:
      - db

volumes:
  authelia-redis:

networks:
  default:
    name: apps
    external: true
  db:
