version: '3'
secrets:
  JWT_SECRET:
    file: ./secrets/JWT_SECRET
  STORAGE_ENCRYPTION_KEY:
    file: ./secrets/STORAGE_ENCRYPTION_KEY
  NOTIFIER_SMTP_PASSWORD:
    file: ./secrets/NOTIFIER_SMTP_PASSWORD

services:
  authelia:
    container_name: authelia
    image: authelia/authelia:latest
    restart: unless-stopped
    # expose:
    #   - 9091
    secrets: [JWT_SECRET, STORAGE_ENCRYPTION_KEY, NOTIFIER_SMTP_PASSWORD]
    environment:
      AUTHELIA_JWT_SECRET_FILE: /run/secrets/JWT_SECRET
      AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE: /run/secrets/STORAGE_ENCRYPTION_KEY
      AUTHELIA_NOTIFIER_SMTP_PASSWORD_FILE: /run/secrets/NOTIFIER_SMTP_PASSWORD
    volumes:
      - ./config:/config
    user: 1000:1000

  redis:
    image: redis
    restart: unless-stopped
    volumes:
      - authelia-redis:/data

volumes:
  authelia-redis:

networks:
  default:
    name: apps
    external: true