version: '3'
services:
  nextcloud:
    image: linuxserver/nextcloud:latest
    container_name: nextcloud
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
    volumes:
      - ./config:/config
      - /mnt/4t/cloud:/data
    # ports:
    #   - 443:443
    restart: unless-stopped

networks:
  default:
    name: apps
    external: true
